<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Class1.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Sardine.Core.Views.WPF" Version="1.1.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sardine.Test.FictiveWorkload\Sardine.Test.FictiveWorkload.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="FictiveWorkload_UI.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
  </ItemGroup>

</Project>
